language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL

install:
  - sudo apt-get update
  - sudo apt-get install -y cmake libboost-all-dev libevent-dev 

script: mkdir build && cd build && cmake .. && make 

branches:
  only:
    - master

os:
  - linux

