version: "{branch}-ci-{build}"
clone_depth: 5 
os: unstable

environment:
  BOOST_ROOT: c:/Libraries/boost
  BOOST_LIBRARYDIR: c:/Libraries/boost/stage/lib

init:
  - cmd: cmake --version
  - cmd: msbuild /version

build_script:
  - md build
  - cd build
  - cmake -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" .. 
  - cmake --build . 

branches:
  only:
    - master

