version: "{branch}-ci-{build}"
clone_depth: 5 

os: Visual Studio 2015

platform:
  - x64

configuration:
  - Release

environment:
  global:
    BOOST_INCLUDEDIR: C:/Libraries/boost_1_59_0
    BOOST_LIBRARYDIR: C:/Libraries/boost_1_59_0/lib64-msvc-14.0
    BUILD_TYPE: Release
    CMAKE_INCLUDE_PATH: C:/projects/dakara-server/deps/libevent_vc120/build/native/include
    CMAKE_LIBRARY_PATH: C:/projects/dakara-server/deps/libevent_vc120/build/native/bin

init:
  - cmd: cmake --version
  - cmd: msbuild /version
  - cmd: echo %platform%

before_build:
  - mkdir deps
  - mkdir deps\include
  - mkdir deps\lib
  - nuget install libevent_vc120 -OutputDirectory deps -ExcludeVersion 

build_script:
#  - dir /s /p %BOOST_ROOT%
#  - dir /s /p deps
  - echo %configuration%
  - mkdir build
  - pushd .
  - cd build
  - cmake --version
  - cmake -G "Visual Studio 14 2015 Win64" ..
  - cmake --build .

build:
  parallel: true
  verbosity: detailed

after_build:
  - 7z a -xr!dakaraserver.dir dakara-server-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_NUMBER%-%APPVEYOR_JOB_ID%.7z %APPVEYOR_BUILD_FOLDER%

artifacts:
  - path: '*.7z'

deploy:
  - provider: FTP
    server:
      secure: C6tkq+q/3l6LiQ4CGNgMhLWvzaajInbUEeruKHhC2lo=
    username:
      secure: 4j+6jfu8uhGJvd/WBx0RYw==
    password:
      secure: b0B/dtBHOEaFQAqiyT4Ysg==
    folder: /dakara-server
    enable_ssl: true
    active_mode: false
    artifact:

branches:
  only:
    - master
