version: "{branch}-ci-{build}"
clone_depth: 5 

platform:
  - Win32
  - x64

environment:
  BOOST_ROOT: c:/Libraries/boost
  BOOST_LIBRARYDIR: c:/Libraries/boost/stage/lib

init:
  - cmd: cmake --version
  - cmd: msbuild /version
  - cmd: echo %platform%

before_build:
  - md build
  - cd build
#  - cmake -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" .. 
#  - cmake --build . 
#  - cmd: if "%platform%"=="Win32" cmake -G "Visual Studio 12" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON" ..
#  - cmd: if "%platform%"=="x64" cmake -G "Visual Studio 12 Win64" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBOOST_TEST_HEADER_ONLY="ON" ..
  - cmd: cmake -G "Visual Studio 12" -DCMAKE_BUILD_TYPE=%configuration% -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..  

build:
  project: C:\projects\dakara-server\build\dakaraserver.sln
  parallel: true
  verbosity: detailed

branches:
  only:
    - master

